# Generated by Django 3.2.7 on 2021-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
