# Generated by Django 3.2.7 on 2021-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0002_resident_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resident/pictures'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
