# Generated by Django 3.2.7 on 2021-09-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0005_auto_20210917_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Otro'), (1, 'Masculino'), (2, 'Femenino')], default=0),
        ),
        migrations.AlterField(
            model_name='resident',
            name='prepaid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='residency.prepaid'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Baja')], default=1),
        ),
    ]
