# Generated by Django 3.2.7 on 2021-09-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0006_auto_20210917_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
