# Generated by Django 3.2.7 on 2021-09-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0007_alter_resident_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='id_type',
            field=models.IntegerField(choices=[(0, 'DNI'), (1, 'LC'), (2, 'LE'), (3, 'Pasaporte')], default=0),
        ),
        migrations.AlterField(
            model_name='resident',
            name='marital_status',
            field=models.IntegerField(choices=[(0, 'Casado/a'), (1, 'Divorciado/a'), (2, 'Viudo/a'), (3, 'Soltero/a')], default=0),
        ),
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='residency/static/resident/pictures'),
        ),
    ]
