# Generated by Django 3.2.7 on 2021-09-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0008_auto_20210919_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('commercial_name', models.CharField(max_length=200)),
                ('pharmaceutical_form', models.IntegerField(choices=[(0, 'Cápsulas'), (1, 'Crema'), (2, 'Dosis'), (3, 'Gel'), (4, 'Gotas'), (5, 'Inyectable'), (6, 'Jarabe'), (7, 'Loción'), (8, 'Paff'), (9, 'Parche'), (10, 'Polvo'), (11, 'Pomada'), (12, 'Suplemento'), (13, 'Otro')], default=13)),
                ('measurement_unit', models.IntegerField(choices=[(0, 'Unidad'), (1, 'mg'), (2, 'g'), (3, 'kg'), (4, 'ml')], default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='residency/pictures/medication')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('lunch', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('tea', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('dinner', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('medication_status', models.IntegerField(choices=[(0, 'Activo'), (1, 'Suspendido'), (3, 'SOS')], default=0)),
                ('prescription_date', models.DateField(help_text='Formato AAAA-mm-dd')),
                ('last_registry_date', models.DateTimeField(auto_now_add=True)),
                ('in_pillbox', models.BooleanField(default=False)),
                ('floor', models.IntegerField(choices=[(0, 'Planta baja'), (1, 'Planta alta')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(help_text='Formato AAAA-mm-dd'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='residency/pictures/resident'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='residency.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residency.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residency.resident'),
        ),
    ]
