# Generated by Django 3.2.7 on 2021-09-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0009_auto_20210920_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
