# Generated by Django 3.2.7 on 2021-09-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0010_medication_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='measurement_unit',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml')], default='Unidad', max_length=10),
        ),
    ]
