# Generated by Django 3.2.7 on 2021-09-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0011_alter_medication_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='pharmaceutical_form',
            field=models.CharField(choices=[('Cápsulas', 'Cápsulas'), ('Crema', 'Crema'), ('Dosis', 'Dosis'), ('Gel', 'Gel'), ('Gotas', 'Gotas'), ('Inyectable', 'Inyectable'), ('Jarabe', 'Jarabe'), ('Loción', 'Loción'), ('Paff', 'Paff'), ('Parche', 'Parche'), ('Polvo', 'Polvo'), ('Pomada', 'Pomada'), ('Suplemento', 'Suplemento'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='floor',
            field=models.CharField(choices=[('Planta baja', 'Planta baja'), ('Planta alta', 'Planta alta')], default='Planta baja', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication_status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('SOS', 'SOS')], default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='id_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('LC', 'LC'), ('LE', 'LE'), ('Pasaporte', 'Pasaporte')], default='DNI', max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='marital_status',
            field=models.CharField(choices=[('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Soltero/a', 'Soltero/a')], default='Casado/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja')], default='Activo', max_length=50),
        ),
    ]
