# Generated by Django 3.2.7 on 2021-09-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0012_auto_20210921_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
