# Generated by Django 3.2.7 on 2021-09-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0013_prescription_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='total_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.CharField(max_length=200),
        ),
    ]
