# Generated by Django 3.2.7 on 2021-09-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0014_auto_20210921_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='breakfast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dinner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lunch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='tea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
