# Generated by Django 3.2.7 on 2021-09-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0015_auto_20210921_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='breakfast',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dinner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lunch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='tea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
