# Generated by Django 3.2.7 on 2021-09-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0016_auto_20210921_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='total_per_day',
        ),
    ]
