# Generated by Django 3.2.7 on 2021-09-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0017_remove_prescription_total_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='residency.medication'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='residency.resident'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='residency.medication'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='residency.prescription'),
        ),
    ]
