# Generated by Django 3.2.7 on 2021-09-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0018_auto_20210922_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='breakfast',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dinner',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='lunch',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='tea',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.FloatField(),
        ),
    ]
