# Generated by Django 3.2.7 on 2021-09-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0019_auto_20210922_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='amount',
            new_name='avaliable',
        ),
    ]
