# Generated by Django 3.2.7 on 2021-09-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0020_rename_amount_stock_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resident'),
        ),
    ]
