# Generated by Django 3.2.7 on 2021-09-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0021_alter_resident_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resident/photos'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('billing_info', models.CharField(max_length=20, unique=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='residency.resident')),
            ],
        ),
    ]
