# Generated by Django 3.2.7 on 2021-09-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0022_auto_20210927_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='resident',
        ),
        migrations.AddField(
            model_name='resident',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='residency.tutor'),
            preserve_default=False,
        ),
    ]
