# Generated by Django 3.2.7 on 2021-09-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0023_auto_20210927_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
