# Generated by Django 3.2.7 on 2021-09-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0024_tutor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='residency.tutor'),
        ),
    ]
